-- MySQL Script generated by MySQL Workbench
-- Wed Aug 27 19:44:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema encuestabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema encuestabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `encuestabd` DEFAULT CHARACTER SET utf8mb3 ;
USE `encuestabd` ;

-- -----------------------------------------------------
-- Table `encuestabd`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestabd`.`ciudad` (
  `idCIUDAD` INT NOT NULL AUTO_INCREMENT,
  `Municipio` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCIUDAD`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `encuestabd`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestabd`.`encuesta` (
  `idEncuesta` INT NOT NULL AUTO_INCREMENT,
  `0` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `1` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `2` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `3` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `4` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `5` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `6` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `7` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `8` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  `9` ENUM('NUNCA', 'AVECES', 'REGULARMENTE', 'SIEMPRE') NOT NULL,
  PRIMARY KEY (`idEncuesta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `encuestabd`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestabd`.`facultad` (
  `idFACULTAD` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idFACULTAD`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `encuestabd`.`generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestabd`.`generales` (
  `idGENERALES` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `SEXO` ENUM('MASCULINO', 'FEMENINO') NOT NULL,
  `CIUDAD_idCIUDAD` INT NOT NULL,
  `FACULTAD_idFACULTAD` INT NOT NULL,
  PRIMARY KEY (`idGENERALES`, `CIUDAD_idCIUDAD`, `FACULTAD_idFACULTAD`),
  INDEX `fk_GENERALES_CIUDAD1_idx` (`CIUDAD_idCIUDAD` ASC) VISIBLE,
  INDEX `fk_GENERALES_FACULTAD1_idx` (`FACULTAD_idFACULTAD` ASC) VISIBLE,
  CONSTRAINT `fk_GENERALES_CIUDAD1`
    FOREIGN KEY (`CIUDAD_idCIUDAD`)
    REFERENCES `encuestabd`.`ciudad` (`idCIUDAD`),
  CONSTRAINT `fk_GENERALES_FACULTAD1`
    FOREIGN KEY (`FACULTAD_idFACULTAD`)
    REFERENCES `encuestabd`.`facultad` (`idFACULTAD`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `encuestabd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestabd`.`user` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('USER', 'ADMIN') NOT NULL,
  `GENERALES_idGENERALES` INT NOT NULL,
  `GENERALES_CIUDAD_idCIUDAD` INT NOT NULL,
  `GENERALES_FACULTAD_idFACULTAD` INT NOT NULL,
  `encuesta_completada` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idUSER`, `GENERALES_idGENERALES`, `GENERALES_CIUDAD_idCIUDAD`, `GENERALES_FACULTAD_idFACULTAD`),
  INDEX `fk_user_GENERALES1_idx` (`GENERALES_idGENERALES` ASC, `GENERALES_CIUDAD_idCIUDAD` ASC, `GENERALES_FACULTAD_idFACULTAD` ASC) VISIBLE,
  CONSTRAINT `fk_user_GENERALES1`
    FOREIGN KEY (`GENERALES_idGENERALES` , `GENERALES_CIUDAD_idCIUDAD` , `GENERALES_FACULTAD_idFACULTAD`)
    REFERENCES `encuestabd`.`generales` (`idGENERALES` , `CIUDAD_idCIUDAD` , `FACULTAD_idFACULTAD`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO CIUDAD (Municipio, Departamento) VALUES
-- Managua
('Managua', 'Managua'),
('Tipitapa', 'Managua'),
('Ciudad Sandino', 'Managua'),

-- León
('León', 'León'),
('Nagarote', 'León'),

-- Chinandega
('Chinandega', 'Chinandega'),
('Corinto', 'Chinandega'),

-- Masaya
('Masaya', 'Masaya'),
('Nindirí', 'Masaya'),

-- Granada
('Granada', 'Granada'),

-- Carazo
('Jinotepe', 'Carazo'),
('Diriamba', 'Carazo'),

-- Rivas
('Rivas', 'Rivas'),
('San Juan del Sur', 'Rivas'),

-- Matagalpa
('Matagalpa', 'Matagalpa'),
('Jinotega', 'Jinotega'),

-- Estelí
('Estelí', 'Estelí'),

-- Madriz
('Somoto', 'Madriz'),

-- Nueva Segovia
('Ocotal', 'Nueva Segovia'),
('Jalapa', 'Nueva Segovia'),

-- Boaco
('Boaco', 'Boaco'),

-- Chontales
('Juigalpa', 'Chontales'),

-- Río San Juan
('San Carlos', 'Río San Juan'),

-- RAAN (Caribe Norte)
('Bilwi', 'Caribe Norte'),
('Waspam', 'Caribe Norte'),

-- RAAS (Caribe Sur)
('Bluefields', 'Caribe Sur'),
('Nueva Guinea', 'Caribe Sur');

INSERT INTO FACULTAD (Nombre) VALUES
('Facultad de Ciencias y Tecnología'),
('Facultad de Ciencias de la Educación y Humanidades'),
('Facultad de Ciencias Médicas'),
('Facultad de Ciencias Económicas y Empresariales'),
('Facultad de Ciencias Jurídicas y Sociales'),
('Facultad de Odontología'),
('Facultad de Química y Farmacia'),
('Facultad de Ciencias e Ingeniería'),
('Facultad de Ciencias Veterinarias'),
('Facultad Multidisciplinaria de Chontales'),
('Facultad Regional Multidisciplinaria de Estelí (FAREM-Estelí)'),
('Facultad Regional Multidisciplinaria de Jinotega (FAREM-Jinotega)'),
('Facultad Regional Multidisciplinaria de Matagalpa (FAREM-Matagalpa)'),
('Facultad Regional Multidisciplinaria de Somoto (FAREM-Somoto)');

INSERT INTO `encuestabd`.`generales` 
(`Nombre`, `Apellido`, `SEXO`, `CIUDAD_idCIUDAD`, `FACULTAD_idFACULTAD`)
VALUES 
('Admin', 'Principal', 'MASCULINO', 1, 1);


INSERT INTO `encuestabd`.`user` 
(`username`, `password`, `rol`, `GENERALES_idGENERALES`, `GENERALES_CIUDAD_idCIUDAD`, `GENERALES_FACULTAD_idFACULTAD`, `encuesta_completada`) 
VALUES 
('admin', '123', 'ADMIN', 1, 1, 1, 1);



